### PR TITLE
Add additive radar-CML merging with IDW and with Krignig, plus example data

### PR DESCRIPTION
**Pull request by eoydvin**
This PR implements parts of what is discussed in #2 

 - creates 5min aggregated CML, rain gauge and radar data for the openmerge dataset

src/mergeplg/merge.py:
 - first implementation of merging

src/mergeplg/interpolator.py and src/mergeplg/idw.py:
 - IDW interpolator functions from python

### CODE REVIEW

**Comment by cchwala** [comment]
A lot of green check marks now!  🎉

Thanks @eoydvin. I will look into the details next week.

**Comment by cchwala** [comment]
You can remove the `pypy-3.10` test. We do not test pypy in `poligrain`.

**Comment by eoydvin** [comment]
> A lot of green check marks now! 🎉
> 
> Thanks @eoydvin. I will look into the details next week.



> You can remove the `pypy-3.10` test runs (I guess somewhere in the CI config). We do not test pypy in `poligrain`.

**Comment by eoydvin** [comment]
I also have some KED prototype files now, but then the tests will not run anymore. Should we just keep it like this for now then?

**Comment by cchwala** [comment]
Yes. Let's keep this PR focused on what you already have and add KED in another PR.

I will have a look this week.

**Comment by cchwala** [comment]
Sorry for the long delay 🙈. I now finally had a quick look at the code and notebook. Looks really good 👏 👏 👏 . Of course, we will have to see/discuss how we define a common higher-level interface for the different functions. But this is a very good starting point. I am merging this now. Once I have my PR #6 ready or merged we should start the discussion about aligning the code, i.e. finding the mentioned common "interface".

**Pull request merged**
